source 'https://github.com/JY726/LJYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'LJYAPIsKit_Example' do
  pod 'LJYAPIsKit', :path => '../'

  target 'LJYAPIsKit_Tests' do
    inherit! :search_paths

    
  end
end
